#file: noinspection SpellCheckingInspection
name: material_themes_widgets
description: Widgets that use the Material Themes Manager by default in order to allow for theme udpates
version: 1.7.2
homepage: https://playtcubed.com

environment:
  sdk: '>=3.3.0-71.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  material_themes_manager: ^1.4.0
  provider: ^6.0.5
  circular_profile_avatar: ^2.0.5
  flutter_polygon: ^0.3.0+2
  assets_audio_player: ^3.1.1
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: